"""Detects installed package managers and clears their regenerable caches.

Every cache touched here (downloaded wheels, tarballs, build artifacts) is
rebuilt or refetched by the tool on demand, so clearing only costs bandwidth
on the next install. Also scans project folders for per-project cache dirs
via PROJECT_CACHE_CATEGORIES.
"""

import json
import os
import platform
import shutil
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional
import logging

from cortex_unified.core import proc as _proc
from cortex_unified.core.config import Config

@dataclass
class Package:
    """Single installed package as reported by a manager's list command."""
    name: str
    version: str
    size: int
    install_date: Optional[datetime] = None
    dependencies: List[str] = None
    is_orphaned: bool = False
    manager: str = ""
    
    def __post_init__(self):
        if self.dependencies is None:
            self.dependencies = []
        """__post_init__."""
        """__post_init__."""

@dataclass
class PackageManager:
    """Detected manager executable with its resolved cache/config paths."""
    name: str
    executable: str
    version: str
    cache_path: Optional[Path] = None
    config_path: Optional[Path] = None
    is_available: bool = False
    health_status: str = "unknown"

@dataclass
class CleanupResult:
    """Outcome of one cache-clean operation (counts, bytes, errors)."""
    success: bool
    files_removed: int
    space_freed: int
    errors: List[str] = None
    backup_path: Optional[str] = None
    
    def __post_init__(self):
        if self.errors is None:
            self.errors = []
        """__post_init__."""
        """__post_init__."""

@dataclass
class HealthStatus:
    """Post-cleanup health verdict for a single package manager."""
    is_healthy: bool
    issues: List[str] = None
    recommendations: List[str] = None
    
    def __post_init__(self):
        if self.issues is None:
            self.issues = []
        """__post_init__."""
        """__post_init__."""
# Directory-name patterns treated as disposable when scanning project folders.
# Every entry is regenerated by its toolchain on the next build/install, so
# deletion is safe; virtualenvs (.venv/venv/env) are the heavy cases and are
# recreatable from requirements/lockfiles.
PROJECT_CACHE_CATEGORIES = {
    "python": {
        "label": "Python Caches & Virtual Envs",
        "patterns": {
            "__pycache__": "Python bytecode cache",
            ".pytest_cache": "Pytest cache",
            ".mypy_cache": "MyPy cache",
            ".ruff_cache": "Ruff linter cache",
            ".tox": "Tox test environment",
            ".coverage": "Code coverage cache",
            ".ipynb_checkpoints": "Jupyter Notebook checkpoints",
            ".egg-info": "Python egg metadata",
            ".dist-info": "Python dist metadata",
            ".venv": "Python virtual environment",
            "venv": "Python virtual environment",
            "env": "Python virtual environment",
            ".env": "Python virtual environment",
            "pip-wheel-metadata": "Pip wheel metadata cache",
            "htmlcov": "Coverage HTML report cache",
        }
    },
    "node": {
        "label": "Node.js & Web Framework Caches",
        "patterns": {
            "node_modules": "NPM / Yarn / PNPM packages",
            ".next": "Next.js build cache",
            ".nuxt": "Nuxt.js build cache",
            ".turbo": "Turborepo build cache",
            ".vite": "Vite dev server cache",
            ".cache": "Web build cache",
            "out": "Web build output",
            "dist": "Distribution build folder",
            ".parcel-cache": "Parcel bundler cache",
            ".svelte-kit": "SvelteKit build cache",
            ".angular": "Angular build cache",
            ".yarn": "Yarn cache folder",
            ".pnpm-store": "PNPM store cache",
        }
    },
    "rust_go": {
        "label": "Rust & Go Development Caches",
        "patterns": {
            "target": "Cargo Rust build target",
            "pkg": "Go module cache",
        }
    },
    "java_dotnet": {
        "label": "Java, Gradle, Maven & .NET Caches",
        "patterns": {
            ".gradle": "Gradle build cache",
            "build": "Build directory",
            ".m2": "Maven repository cache",
            "bin": "Compiled binary output",
            "obj": "Compiled object files",
            ".vs": "Visual Studio cache",
            ".idea": "IntelliJ / JetBrains cache",
        }
    },
    "cpp_cmake": {
        "label": "C/C++ & CMake Build Caches",
        "patterns": {
            "cmake-build-debug": "CMake Debug build",
            "cmake-build-release": "CMake Release build",
            "cmake-build-relwithdebinfo": "CMake RelWithDebInfo build",
            ".ninja": "Ninja build files",
            "CMakeFiles": "CMake build files",
        }
    },
    "mobile_other": {
        "label": "Mobile, Ruby & PHP Caches",
        "patterns": {
            ".dart_tool": "Dart & Flutter tool cache",
            "DerivedData": "Xcode build data",
            ".externalNativeBuild": "Android NDK native build cache",
            ".cxx": "Android C++ native build cache",
            "vendor": "Composer / Ruby vendor directory",
            ".bundle": "Ruby bundler cache",
        }
    }
}


class PackageManagerCleaner:
    """Cleans caches for well-known package managers across platforms.

    Detection probes PATH per-OS; cache locations are queried from each tool
    itself rather than hard-coded, so custom cache dirs are honored. Package
    lists are backed up under ~/.cortex_cleaner_backups before any destructive
    operation.
    """
    
    def __init__(self, config: Config = None):
        """Build manager definitions, logger, and the backup directory.

        Args:
            config: Optional application Config; a default is built if omitted.
        """
        self.config = config or Config()
        self.logger = logging.getLogger(__name__)
        
        self.package_managers = {
            "pip": {
                "executable": "pip",
                "cache_commands": ["cache", "dir"],
                "list_command": ["list"],
                "cache_clean_command": ["cache", "purge"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "npm": {
                "executable": "npm",
                "cache_commands": ["config", "get", "cache"],
                "list_command": ["list", "-g", "--depth=0"],
                "cache_clean_command": ["cache", "clean", "--force"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "yarn": {
                "executable": "yarn",
                "cache_commands": ["cache", "dir"],
                "list_command": ["global", "list"],
                "cache_clean_command": ["cache", "clean"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "pnpm": {
                "executable": "pnpm",
                "cache_commands": ["store", "path"],
                "list_command": ["list", "-g"],
                "cache_clean_command": ["store", "prune"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "bun": {
                "executable": "bun",
                "cache_commands": ["pm", "cache", "ls"],
                "list_command": ["pm", "ls", "-g"],
                "cache_clean_command": ["pm", "cache", "rm"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "conda": {
                "executable": "conda",
                "cache_commands": ["info", "--json"],
                "list_command": ["list"],
                "cache_clean_command": ["clean", "--all", "-y"],
                "platforms": ["windows", "linux", "darwin"]
            },
            "apt": {
                "executable": "apt",
                "cache_commands": ["config", "dump"],
                "list_command": ["list", "--installed"],
                "cache_clean_command": ["clean"],
                "platforms": ["linux"]
            },
            "dnf": {
                "executable": "dnf",
                "cache_commands": ["config-manager", "--dump"],
                "list_command": ["list", "installed"],
                "cache_clean_command": ["clean", "all"],
                "platforms": ["linux"]
            },
            "pacman": {
                "executable": "pacman",
                "cache_commands": ["-Sc"],
                "list_command": ["-Q"],
                "cache_clean_command": ["-Scc", "--noconfirm"],
                "platforms": ["linux"]
            },
            "brew": {
                "executable": "brew",
                "cache_commands": ["--cache"],
                "list_command": ["list"],
                "cache_clean_command": ["cleanup", "-s"],
                "platforms": ["darwin", "linux"]
            },
            "chocolatey": {
                "executable": "choco",
                "cache_commands": ["config", "get", "cacheLocation"],
                "list_command": ["list", "--local-only"],
                "cache_clean_command": ["cache", "clean"],
                "platforms": ["windows"]
            },
            "cargo": {
                "executable": "cargo",
                "cache_commands": ["--version"],
                "list_command": ["--version"],
                "cache_clean_command": ["clean"],
                "platforms": ["windows", "linux", "darwin"],
                "cache_path_override": str(Path.home() / ".cargo" / "registry"),
                "extra_cache_paths": [str(Path.home() / ".cargo" / "git"), str(Path.home() / ".cargo" / "registry" / "cache")],
            },
            "rustup": {
                "executable": "rustup",
                "cache_commands": ["--version"],
                "list_command": ["toolchain", "list"],
                "cache_clean_command": ["toolchain", "uninstall"],
                "platforms": ["windows", "linux", "darwin"],
                "cache_path_override": str(Path.home() / ".rustup" / "toolchains"),
                "opt_in": True,
            },
            "scoop": {
                "executable": "scoop",
                "cache_commands": ["config", "cache_path"],
                "list_command": ["list"],
                "cache_clean_command": ["cache", "rm", "*"],
                "platforms": ["windows"],
                "cache_path_override": str(Path.home() / "scoop" / "cache"),
            },
            "winget": {
                "executable": "winget",
                "cache_commands": ["--version"],
                "list_command": ["list"],
                "cache_clean_command": ["--help"],
                "platforms": ["windows"],
                "cache_path_override": str(Path.home() / "AppData" / "Local" / "Packages" / "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe" / "LocalCache"),
            },
        }
        
        self.detected_managers: List[PackageManager] = []
        self.backup_dir = Path.home() / ".cortex_cleaner_backups"
        self.backup_dir.mkdir(exist_ok=True)
    
    def detect_package_managers(self) -> List[PackageManager]:
        """Probe PATH for supported managers on the current OS.

        A manager counts as detected only if its executable exists and answers
        --version; failures are logged at debug level and skipped.
        """
        self.detected_managers = []
        current_platform = platform.system().lower()
        
        for name, config in self.package_managers.items():
            if current_platform not in config["platforms"]:
                continue
            try:
                executable_path = shutil.which(config["executable"])
                if not executable_path:
                    continue
                version = self._get_package_manager_version(name, config["executable"])
                if not version:
                    continue
                cache_path = self._get_cache_path(name, config)
                manager = PackageManager(
                    name=name,
                    executable=executable_path,
                    version=version,
                    cache_path=cache_path,
                    is_available=True,
                    health_status="healthy"
                )
                self.detected_managers.append(manager)
                self.logger.info(f"Detected package manager: {name} v{version}")
            except Exception as e:
                self.logger.debug(f"Failed to detect {name}: {e}")
                continue
        
        return self.detected_managers
    
    def _get_package_manager_version(self, name: str, executable: str) -> Optional[str]:
        """Return the version string, parsed per-tool from --version output."""
        try:
            result = _proc.run([executable, "--version"], text=True, timeout=10)
            if result.returncode == 0:
                output = result.stdout.strip()
                if name == "pip":
                    # pip 21.3.1 from /usr/lib/python3/dist-packages/pip (python 3.9)
                    parts = output.split()
                    if len(parts) >= 2:
                        return parts[1]
                elif name in ["npm", "yarn", "conda"]:
                    return output
                elif name in ["apt", "dnf", "pacman", "brew"]:
                    # These print banner lines; the version token is on line 1
                    first_line = output.split('\n')[0]
                    parts = first_line.split()
                    for part in parts:
                        if part[0].isdigit():
                            return part
                elif name == "chocolatey":
                    return output
            
        except Exception as e:
            self.logger.debug(f"Failed to get version for {name}: {e}")
        
        return None
    
    def _get_cache_path(self, name: str, config: Dict) -> Optional[Path]:
        """Get cache directory path for a package manager."""
        # Hard overrides for cargo/scoop/rustup where the tool has no --cache command
        override = config.get("cache_path_override")
        if override:
            p = Path(override).expanduser()
            # For cargo we honour CARGO_HOME if set
            if name == "cargo":
                cargo_home = os.environ.get("CARGO_HOME")
                if cargo_home:
                    p = Path(cargo_home) / "registry"
            if name == "scoop":
                # scoop config cache_path may override default
                try:
                    result = _proc.run([config["executable"]] + config.get("cache_commands", []),
                                          text=True, timeout=10)
                    if result.returncode == 0 and result.stdout.strip():
                        maybe = Path(result.stdout.strip())
                        if maybe.exists():
                            return maybe
                except Exception:
                    pass
            return p

        try:
            cache_commands = config.get("cache_commands", [])
            if not cache_commands:
                return None
            
            executable = config["executable"]
            
            if name == "pip":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())
            
            elif name == "npm":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())
            
            elif name == "yarn":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())
            
            elif name == "pnpm":
                result = _proc.run([executable] + cache_commands,
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())

            elif name == "bun":
                result = _proc.run([executable] + cache_commands,
                                      text=True, timeout=10)
                if result.returncode == 0:
                    # bun pm cache ls prints list; first line is path-like
                    first = result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""
                    if first and Path(first).exists():
                        return Path(first)
                    return None
            
            elif name == "conda":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    info = json.loads(result.stdout)
                    pkgs_dirs = info.get("pkgs_dirs", [])
                    if pkgs_dirs:
                        return Path(pkgs_dirs[0])
            
            elif name == "brew":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())
            
            elif name == "chocolatey":
                result = _proc.run([executable] + cache_commands, 
                                      text=True, timeout=10)
                if result.returncode == 0:
                    return Path(result.stdout.strip())
            
        except Exception as e:
            self.logger.debug(f"Failed to get cache path for {name}: {e}")
        
        return None
    
    def clean_pip_cache(self, keep_recent_days: int = 7) -> CleanupResult:
        """Delete pip cache files older than keep_recent_days.

        The pip cache holds only downloaded wheels and HTTP responses; pip
        refetches anything missing, so removal is safe. Keeping recent files
        preserves cache hits for imminent reinstalls.

        Args:
            keep_recent_days: Age threshold in days; newer files stay.

        Returns:
            CleanupResult with per-file counts, or a failure result when pip
            is unavailable or its cache dir is missing.
        """
        pip_manager = self._get_manager_by_name("pip")
        if not pip_manager or not pip_manager.cache_path:
            return CleanupResult(False, 0, 0, ["Pip not available or cache path not found"])
        
        try:
            # Snapshot the installed-package list before deleting anything
            backup_path = self._backup_package_lists(["pip"])
            
            files_removed = 0
            space_freed = 0
            errors = []
            
            cache_path = pip_manager.cache_path
            if not cache_path.exists():
                return CleanupResult(False, 0, 0, ["Pip cache directory does not exist"])
            
            cutoff_date = datetime.now() - timedelta(days=keep_recent_days)
            
            for root, dirs, files in os.walk(cache_path):
                for file in files:
                    file_path = Path(root) / file
                    try:
                        file_mtime = datetime.fromtimestamp(file_path.stat().st_mtime)
                        if file_mtime < cutoff_date:
                            file_size = file_path.stat().st_size
                            file_path.unlink()
                            files_removed += 1
                            space_freed += file_size
                    except Exception as e:
                        errors.append(f"Failed to remove {file_path}: {e}")
            
            return CleanupResult(
                success=True,
                files_removed=files_removed,
                space_freed=space_freed,
                errors=errors,
                backup_path=backup_path.get("pip")
            )
            
        except Exception as e:
            return CleanupResult(False, 0, 0, [f"Failed to clean pip cache: {e}"])
    
    def clean_npm_cache(self, verify_integrity: bool = True) -> CleanupResult:
        """Wipe npm's content-addressed cache, then optionally verify it.

        npm caches tarballs/metadata keyed by integrity hash and refetches on
        demand, so wiping is safe. `npm cache verify` afterwards rebuilds the
        index and confirms consistency.

        Args:
            verify_integrity: Run `npm cache verify` after cleaning.

        Returns:
            CleanupResult; space_freed comes from before/after size sampling
            and files_removed is 0 if the tool does not report discrete file counts.
        """
        npm_manager = self._get_manager_by_name("npm")
        if not npm_manager:
            return CleanupResult(False, 0, 0, ["NPM not available"])
        
        try:
            backup_path = self._backup_package_lists(["npm"])
            
            cache_size_before = self._get_cache_size(npm_manager.cache_path)
            
            result = _proc.run([npm_manager.executable, "cache", "clean", "--force"], 
                                  text=True, timeout=60)
            
            if result.returncode != 0:
                return CleanupResult(False, 0, 0, [f"NPM cache clean failed: {result.stderr}"])
            
            if verify_integrity:
                verify_result = _proc.run([npm_manager.executable, "cache", "verify"], 
                                             text=True, timeout=60)
                if verify_result.returncode != 0:
                    return CleanupResult(False, 0, 0, [f"NPM cache verification failed: {verify_result.stderr}"])
            
            cache_size_after = self._get_cache_size(npm_manager.cache_path)
            space_freed = cache_size_before - cache_size_after
            
            return CleanupResult(
                success=True,
                files_removed=1,  # We don't know exact file count
                space_freed=space_freed,
                backup_path=backup_path.get("npm")
            )
            
        except Exception as e:
            return CleanupResult(False, 0, 0, [f"Failed to clean npm cache: {e}"])
    
    def clean_system_packages(self, package_manager: str) -> CleanupResult:
        """Run a system manager's native cache-clean command.

        Applies to apt/dnf/pacman/brew/chocolatey-style managers; each command
        drops only downloaded archives/metadata that get refetched on demand.

        Args:
            package_manager: Name key from self.package_managers.

        Returns:
            CleanupResult with space_freed measured before/after the run.
        """
        manager = self._get_manager_by_name(package_manager)
        if not manager:
            return CleanupResult(False, 0, 0, [f"{package_manager} not available"])
        
        try:
            backup_path = self._backup_package_lists([package_manager])
            
            cache_size_before = self._get_cache_size(manager.cache_path)
            
            config = self.package_managers[package_manager]
            clean_command = [manager.executable] + config["cache_clean_command"]
            
            result = _proc.run(clean_command, text=True, timeout=120)
            
            if result.returncode != 0:
                return CleanupResult(False, 0, 0, [f"{package_manager} clean failed: {result.stderr}"])
            
            cache_size_after = self._get_cache_size(manager.cache_path)
            space_freed = cache_size_before - cache_size_after
            
            return CleanupResult(
                success=True,
                files_removed=1,  # We don't know exact file count
                space_freed=space_freed,
                backup_path=backup_path.get(package_manager)
            )
            
        except Exception as e:
            return CleanupResult(False, 0, 0, [f"Failed to clean {package_manager}: {e}"])
    
    def find_orphaned_packages(self, package_manager: str) -> List[Package]:
        """Dispatch to per-manager orphan detection.

        Orphans are packages nothing else depends on (safe-to-remove
        candidates). Unsupported managers yield [] with a warning.

        Args:
            package_manager: Manager name (pip, npm, apt, dnf, pacman, brew).

        Returns:
            List of Package records; empty on error or unsupported manager.
        """
        manager = self._get_manager_by_name(package_manager)
        if not manager:
            return []
        
        try:
            if package_manager == "pip":
                return self._find_pip_orphaned_packages(manager)
            elif package_manager == "npm":
                return self._find_npm_orphaned_packages(manager)
            elif package_manager == "apt":
                return self._find_apt_orphaned_packages(manager)
            elif package_manager == "dnf":
                return self._find_dnf_orphaned_packages(manager)
            elif package_manager == "pacman":
                return self._find_pacman_orphaned_packages(manager)
            elif package_manager == "brew":
                return self._find_brew_orphaned_packages(manager)
            else:
                self.logger.warning(f"Orphaned package detection not implemented for {package_manager}")
                return []
                
        except Exception as e:
            self.logger.error(f"Failed to find orphaned packages for {package_manager}: {e}")
            return []
    
    def _find_pip_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """List installed pip packages without flagging any as orphaned.

        True orphan detection would require cross-referencing requirements
        files; this simplified pass reports is_orphaned=False everywhere.
        """
        try:
            result = _proc.run([manager.executable, "list", "--format=json"], 
                                  text=True, timeout=30)
            if result.returncode != 0:
                return []
            
            packages_data = json.loads(result.stdout)
            packages = []
            
            for pkg_data in packages_data:
                package = Package(
                    name=pkg_data["name"],
                    version=pkg_data["version"],
                    size=0,  # Pip doesn't provide size info easily
                    manager="pip",
                    is_orphaned=False  # Would need more sophisticated analysis
                )
                packages.append(package)
            
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find pip orphaned packages: {e}")
            return []
    
    def _find_npm_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """Find extraneous / unreferenced npm packages."""
        try:
            result = _proc.run([manager.executable, "ls", "--json", "--depth=0"], 
                                  text=True, timeout=30)
            if not result.stdout.strip():
                return []
            
            packages_data = json.loads(result.stdout)
            packages = []
            deps = packages_data.get("dependencies", {})
            for name, info in deps.items():
                if isinstance(info, dict) and (info.get("extraneous") or info.get("invalid")):
                    packages.append(Package(
                        name=name,
                        version=info.get("version", "unknown"),
                        size=0,
                        manager="npm",
                        is_orphaned=True,
                    ))
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find npm orphaned packages: {e}")
            return []
    
    def _find_apt_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """Cross-references auto-installed packages with autoremove dry-run."""
        try:
            orphaned_result = _proc.run(["apt", "autoremove", "--dry-run"], 
                                           text=True, timeout=30)
            
            packages = []
            if orphaned_result.returncode == 0:
                collecting = False
                for line in orphaned_result.stdout.splitlines():
                    if "The following packages will be REMOVED:" in line:
                        collecting = True
                        continue
                    if collecting:
                        if line.startswith(" ") or line.startswith("\t"):
                            for pkg in line.strip().split():
                                pkg_name = pkg.strip("*").strip()
                                if pkg_name:
                                    packages.append(Package(
                                        name=pkg_name,
                                        version="unknown",
                                        size=0,
                                        manager="apt",
                                        is_orphaned=True,
                                    ))
                        else:
                            break
            
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find apt orphaned packages: {e}")
            return []
    
    def _find_dnf_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """Runs `dnf repoquery --unneeded` or `dnf leaves` to locate unreferenced packages."""
        try:
            result = _proc.run([manager.executable, "repoquery", "--unneeded"], 
                                  text=True, timeout=30)
            if result.returncode != 0:
                result = _proc.run([manager.executable, "leaves"], 
                                      text=True, timeout=30)
            if result.returncode != 0:
                return []
            
            packages = []
            for line in result.stdout.splitlines():
                pkg_name = line.strip()
                if pkg_name and not pkg_name.startswith("Last metadata"):
                    packages.append(Package(
                        name=pkg_name,
                        version="unknown",
                        size=0,
                        manager="dnf",
                        is_orphaned=True,
                    ))
            
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find dnf orphaned packages: {e}")
            return []
    
    def _find_pacman_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """`pacman -Qtdq` lists dependency packages nothing requires anymore;
        each name is returned as an orphaned Package (version unknown).
        """
        try:
            result = _proc.run([manager.executable, "-Qtdq"], 
                                  text=True, timeout=30)
            if result.returncode != 0:
                return []
            
            orphaned_names = result.stdout.strip().split('\n')
            packages = []
            
            for name in orphaned_names:
                if name.strip():
                    package = Package(
                        name=name.strip(),
                        version="unknown",
                        size=0,
                        manager="pacman",
                        is_orphaned=True
                    )
                    packages.append(package)
            
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find pacman orphaned packages: {e}")
            return []
    
    def _find_brew_orphaned_packages(self, manager: PackageManager) -> List[Package]:
        """Runs `brew leaves` (installed formulas that no other formula depends on)."""
        try:
            result = _proc.run([manager.executable, "leaves"], 
                                  text=True, timeout=30)
            if result.returncode != 0:
                return []
            
            packages = []
            for line in result.stdout.splitlines():
                formula = line.strip()
                if formula:
                    packages.append(Package(
                        name=formula,
                        version="unknown",
                        size=0,
                        manager="brew",
                        is_orphaned=True,
                    ))
            
            return packages
            
        except Exception as e:
            self.logger.error(f"Failed to find brew orphaned packages: {e}")
            return []
    
    def backup_package_lists(self) -> Dict[str, str]:
        """Snapshot package lists for every detected manager."""
        return self._backup_package_lists([manager.name for manager in self.detected_managers])
    
    def _backup_package_lists(self, managers: List[str]) -> Dict[str, str]:
        """Write each manager's installed-package listing to a timestamped
        file under ~/.cortex_cleaner_backups before destructive operations,
        so removals can later be audited or replayed.

        Returns:
            Dict mapping manager name to backup file path; only managers
            whose list command succeeded are included.
        """
        backups = {}
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        for manager_name in managers:
            manager = self._get_manager_by_name(manager_name)
            if not manager:
                continue
            
            try:
                backup_file = self.backup_dir / f"{manager_name}_packages_{timestamp}.txt"
                
                config = self.package_managers[manager_name]
                list_command = [manager.executable] + config["list_command"]
                
                result = _proc.run(list_command, text=True, timeout=60)
                
                if result.returncode == 0:
                    with open(backup_file, 'w', encoding='utf-8') as f:
                        f.write(f"# Package list backup for {manager_name}\n")
                        f.write(f"# Created: {datetime.now().isoformat()}\n")
                        f.write(f"# Command: {' '.join(list_command)}\n\n")
                        f.write(result.stdout)
                    
                    backups[manager_name] = str(backup_file)
                    self.logger.info(f"Created backup for {manager_name}: {backup_file}")
                
            except Exception as e:
                self.logger.error(f"Failed to backup {manager_name} package list: {e}")
        
        return backups
    
    def verify_package_manager_health(self, package_manager: str) -> HealthStatus:
        """Post-cleanup sanity check for one manager.

        Runs the manager's list command, probes cache-dir writability with a
        touch/unlink file, and adds tool-specific checks (npm doctor,
        pip check) where applicable.

        Returns:
            HealthStatus; is_healthy is True only when no issues were found.
        """
        manager = self._get_manager_by_name(package_manager)
        if not manager:
            return HealthStatus(False, ["Package manager not found"])
        
        issues = []
        recommendations = []
        
        try:
            config = self.package_managers[package_manager]
            test_command = [manager.executable] + config["list_command"]
            
            result = _proc.run(test_command, text=True, timeout=30)
            
            if result.returncode != 0:
                issues.append(f"Basic command failed: {result.stderr}")
            
            if manager.cache_path and manager.cache_path.exists():
                try:
                    test_file = manager.cache_path / ".health_check"
                    test_file.touch()
                    test_file.unlink()
                except Exception as e:
                    issues.append(f"Cache directory not writable: {e}")
            
            if package_manager == "npm":
                doctor_result = _proc.run([manager.executable, "doctor"], 
                                             text=True, timeout=60)
                if doctor_result.returncode != 0:
                    issues.append("npm doctor reported issues")
                    recommendations.append("Run 'npm doctor' for detailed diagnostics")
            
            elif package_manager == "pip":
                check_result = _proc.run([manager.executable, "check"], 
                                            text=True, timeout=30)
                if check_result.returncode != 0:
                    issues.append("pip check found dependency conflicts")
                    recommendations.append("Run 'pip check' to see dependency issues")
            
        except Exception as e:
            issues.append(f"Health check failed: {e}")
        
        is_healthy = len(issues) == 0
        return HealthStatus(is_healthy, issues, recommendations)
    
    def _get_manager_by_name(self, name: str) -> Optional[PackageManager]:
        """Look up a detected manager by name key; None when absent."""
        for manager in self.detected_managers:
            if manager.name == name:
                return manager
        return None
    
    def _get_cache_size(self, cache_path: Optional[Path]) -> int:
        """Recursive byte total for a cache dir; missing paths count 0."""
        if not cache_path or not cache_path.exists():
            return 0
        
        total_size = 0
        try:
            for root, dirs, files in os.walk(cache_path):
                for file in files:
                    file_path = Path(root) / file
                    try:
                        total_size += file_path.stat().st_size
                    except Exception:
                        continue
        except Exception:
            pass
        
        return total_size
    
    def get_stats(self) -> Dict[str, any]:
        """Get statistics about detected package managers."""
        stats = {
            "detected_managers": len(self.detected_managers),
            "managers": {}
        }
        
        for manager in self.detected_managers:
            cache_size = self._get_cache_size(manager.cache_path)
            stats["managers"][manager.name] = {
                "version": manager.version,
                "cache_path": str(manager.cache_path) if manager.cache_path else None,
                "cache_size": cache_size,
                "cache_size_human": self._format_bytes(cache_size),
                "is_healthy": manager.health_status == "healthy"
            }
        
        return stats
    
    def _format_bytes(self, bytes_count: int) -> str:
        """Format bytes into human-readable format."""
        count = float(bytes_count)
        for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
            if count < 1024.0:
                return f"{count:.1f} {unit}"
            count /= 1024.0
        return f"{count:.1f} PB"

    def scan_caches(self, target_folders: Optional[List[str]] = None, 
                   include_python_projects: bool = False,
                   keep_recent_days: int = 7,
                   enabled_categories: Optional[List[str]] = None,
                   progress_callback: Optional[object] = None,
                   cancel_event: Optional[object] = None) -> List[Dict]:
        """Locate cleanable caches in manager-owned dirs or project trees.

        Without target_folders, reports each detected manager's global cache
        (regenerable downloads). With target_folders, walks those trees and
        matches directory names against PROJECT_CACHE_CATEGORIES.

        Args:
            target_folders: Folders to scan for project caches; None selects
                global package-manager cache scanning instead.
            include_python_projects: Accepted for compatibility; category
                selection is controlled via enabled_categories.
            keep_recent_days: Ignore files younger than this many days (0 = all).
            enabled_categories: Restrict scan to these category IDs
                ('python', 'node', ...); None means all.
            progress_callback: Called as fn(status_text, items_found, total_size).
            cancel_event: threading.Event-like; set() aborts the walk.

        Returns:
            List of resource dicts (schema in _scan_project_caches_in_folder
            and _scan_manager_cache).
        """
        self.detect_package_managers()
        resources = []
        
        if target_folders:
            for folder in target_folders:
                folder_path = Path(folder)
                if folder_path.exists():
                    proj_caches = self._scan_project_caches_in_folder(
                        folder_path,
                        keep_recent_days=keep_recent_days,
                        enabled_categories=enabled_categories,
                        progress_callback=progress_callback,
                        cancel_event=cancel_event
                    )
                    resources.extend(proj_caches)
        else:
            for manager in self.detected_managers:
                if manager.cache_path and manager.cache_path.exists():
                    cache_info = self._scan_manager_cache(manager, keep_recent_days)
                    if cache_info:
                        resources.append(cache_info)
        
        return resources
    
    def _scan_project_caches_in_folder(self, folder: Path, keep_recent_days: int = 0,
                                        enabled_categories: Optional[List[str]] = None,
                                        progress_callback: Optional[object] = None,
                                        cancel_event: Optional[object] = None) -> List[Dict]:
        """Walk `folder` matching directory names against PROJECT_CACHE_CATEGORIES.

        Dotted patterns (e.g. `.egg-info`) also match as name suffixes; each
        hit is reported as a project_cache resource and pruned from deeper
        descent. Loose .pyc/.pyo files are tallied into the running totals
        when the python category is active but emit no per-file resource.
        """
        resources = []
        cutoff_date = datetime.now() - timedelta(days=keep_recent_days) if keep_recent_days > 0 else None
        
        # Build active pattern lookup: pattern_name -> (category_id, description)
        pattern_map = {}
        target_cats = enabled_categories if enabled_categories else list(PROJECT_CACHE_CATEGORIES.keys())
        
        for cat_id in target_cats:
            if cat_id in PROJECT_CACHE_CATEGORIES:
                cat_info = PROJECT_CACHE_CATEGORIES[cat_id]
                for pat, desc in cat_info["patterns"].items():
                    pattern_map[pat] = (cat_id, desc)
        
        def _match_dir(d_name: str) -> Optional[tuple]:
            if d_name in pattern_map:
                return pattern_map[d_name]
            for pat, (cat_id, desc) in pattern_map.items():
                if pat.startswith(".") and d_name.endswith(pat):
                    return (cat_id, desc)
                if pat.endswith("*") and d_name.startswith(pat.rstrip("*")):
                    return (cat_id, desc)
            return None
            """_match_dir."""
            """_match_dir."""
        
        total_items = 0
        total_size = 0
        
        try:
            for root, dirs, files in os.walk(folder):
                if cancel_event and getattr(cancel_event, 'is_set', lambda: False)():
                    break
                
                dirs_to_remove = []
                for d in dirs:
                    dir_path = Path(root) / d
                    match_result = _match_dir(d)
                    
                    if match_result:
                        cat_id, description = match_result
                        try:
                            dir_size, file_cnt = self._get_dir_size(dir_path, cutoff_date)
                            if file_cnt > 0:
                                total_size += dir_size
                                total_items += 1
                                
                                project_name = dir_path.parent.name or folder.name
                                resources.append({
                                    "type": "project_cache",
                                    "category": cat_id,
                                    "path": str(dir_path),
                                    "name": project_name,
                                    "cache_name": d,
                                    "size": dir_size,
                                    "file_count": file_cnt,
                                    "description": f"{description} ({d})",
                                    "manager_name": PROJECT_CACHE_CATEGORIES.get(cat_id, {}).get("label", cat_id.title())
                                })
                                
                                if progress_callback and callable(progress_callback):
                                    progress_callback(
                                        f"Found {d} in {project_name} ({self._format_bytes(dir_size)})",
                                        total_items,
                                        total_size
                                    )
                            dirs_to_remove.append(d)
                        except Exception:
                            pass
                
                for d in dirs_to_remove:
                    dirs.remove(d)
                
                # Loose .pyc/.pyo outside __pycache__: tally only, no resource
                if "python" in target_cats:
                    for file in files:
                        if file.endswith(('.pyc', '.pyo')):
                            file_path = Path(root) / file
                            try:
                                file_stat = file_path.stat()
                                if cutoff_date is None or datetime.fromtimestamp(file_stat.st_mtime) < cutoff_date:
                                    total_size += file_stat.st_size
                            except Exception:
                                pass
        except Exception as e:
            self.logger.error(f"Error scanning folder {folder}: {e}")
        
        return resources
    
    def _scan_manager_cache(self, manager: PackageManager, keep_recent_days: int) -> Optional[Dict]:
        """Summarize one manager's global cache as a resource dict; None when
        the dir is missing or holds no eligible files.
        """
        if not manager.cache_path or not manager.cache_path.exists():
            return None
        
        try:
            total_size, file_count = self._get_dir_size(
                manager.cache_path, 
                datetime.now() - timedelta(days=keep_recent_days)
            )
            
            if file_count > 0:
                return {
                    "type": "package_manager_cache",
                    "path": str(manager.cache_path),
                    "name": manager.name,
                    "size": total_size,
                    "file_count": file_count,
                    "description": f"{manager.name} v{manager.version} cache",
                    "manager_name": manager.name
                }
        except Exception as e:
            self.logger.error(f"Error scanning cache for {manager.name}: {e}")
        
        return None
    
    def _get_dir_size(self, path: Path, cutoff_date: Optional[datetime] = None) -> tuple:
        """Total bytes and file count under path.

        Files modified at/after cutoff_date are excluded; callers use this to
        keep recent cache entries and count only stale ones.
        """
        total_size = 0
        file_count = 0
        
        try:
            for root, dirs, files in os.walk(path):
                for file in files:
                    file_path = Path(root) / file
                    try:
                        file_stat = file_path.stat()
                        
                        if cutoff_date:
                            if datetime.fromtimestamp(file_stat.st_mtime) >= cutoff_date:
                                continue
                        
                        total_size += file_stat.st_size
                        file_count += 1
                    except Exception:
                        pass
        except Exception as e:
            self.logger.debug(f"Error calculating size for {path}: {e}")
        
        return total_size, file_count
    
    def clean_cargo_project(self, target_path: Path, dry_run: bool = True) -> Dict:
        """Run ``cargo clean`` for a Rust project's target dir.

        Args:
            target_path: Path to the target folder (parent must contain Cargo.toml).
            dry_run: When True, only estimates size without deleting.

        Returns:
            Dict with freed/removed/errors, cargo-aware message.
        """
        manifest = target_path.parent / "Cargo.toml"
        if manifest.exists():
            if dry_run:
                size, cnt = self._get_dir_size(target_path, None)
                return {"freed": size, "removed": cnt, "errors": [],
                        "note": f"Dry-run: cargo clean would free {self._format_bytes(size)}"}
            try:
                result = _proc.run(
                    ["cargo", "clean", "--manifest-path", str(manifest)],
                    text=True, timeout=120,
                )
                if result.returncode == 0:
                    # cargo clean removes the target dir itself; freed is pre-size
                    # Already computed by caller; here we just confirm success.
                    return {"freed": 0, "removed": 1, "errors": []}
                return {"freed": 0, "removed": 0, "errors": [result.stderr.strip() or "cargo clean failed"]}
            except Exception as e:
                return {"freed": 0, "removed": 0, "errors": [str(e)]}
        # Fallback to plain file deletion
        return self._cleanup_python_cache(target_path, dry_run)

    def auto_discover_project_caches(
        self,
        enabled_categories: Optional[List[str]] = None,
        keep_recent_days: int = 7,
        progress_callback: Optional[object] = None,
        cancel_event: Optional[object] = None,
        max_depth: int = 4,
    ) -> List[Dict]:
        """Walk all fixed drives for PROJECT_CACHE_CATEGORIES without manual folder.

        Scans common code roots (D:\\code, C:\\Users\\...\\code, ...) plus the
        root of each fixed drive shallowly (max_depth) to catch the 21.9GB
        NexusExplorer/target etc. cases where the user never picked a folder.

        Returns:
            Same resource dicts as scan_caches(target_folders=...).
        """
        from pathlib import Path as _P
        try:
            import psutil
            partitions = psutil.disk_partitions(all=False)
            drive_roots = [p.mountpoint for p in partitions if "fixed" in p.opts.lower() or p.fstype.lower() in ("ntfs", "refs") or (platform.system() == "Windows" and len(p.mountpoint) == 3 and p.mountpoint[1] == ":")]
            # Fallback on Windows if opts empty: enumerate C:, D: ...
            if not drive_roots and platform.system() == "Windows":
                for letter in "CDEFGHIJKLMNOPQRSTUVWXYZ":
                    d = f"{letter}:\\"
                    if _P(d).is_dir():
                        drive_roots.append(d)
        except Exception:
            drive_roots = [str(Path.home().drive) or "C:\\"] if platform.system() == "Windows" else [str(Path.home())]

        # Prefer known code roots first (fast, high hit rate across all drives)
        code_roots: list[str] = []
        try:
            from cortex_unified.analyzers.project_cache_scanner import _known_code_roots
            for p in _known_code_roots():
                code_roots.append(str(p))
        except Exception:
            for cand in [
                Path.home() / "code",
                Path.home() / "Projects",
                Path.home() / "Main_projects",
                Path.home() / "Documents" / "code",
                Path.home() / "source" / "repos",
            ]:
                try:
                    if cand.is_dir():
                        code_roots.append(str(cand))
                except OSError:
                    continue
        # If we have code roots, scan those deeply; otherwise shallow scan drive roots
        if code_roots:
            return self.scan_caches(
                target_folders=code_roots,
                keep_recent_days=keep_recent_days,
                enabled_categories=enabled_categories,
                progress_callback=progress_callback,
                cancel_event=cancel_event,
            )
        # Shallow drive scan with early pruning - use the dedicated scanner if available
        try:
            from cortex_unified.analyzers.project_cache_scanner import ProjectCacheScanner
            scanner = ProjectCacheScanner(
                enabled_categories=enabled_categories,
                keep_recent_days=keep_recent_days,
            )
            return scanner.scan_fixed_drives(
                progress_callback=progress_callback,
                cancel_event=cancel_event,
                max_depth=max_depth,
            )
        except ImportError:
            # Fallback: scan drive roots with our own logic (depth-limited)
            resources: List[Dict] = []
            for root in drive_roots:
                if cancel_event and getattr(cancel_event, 'is_set', lambda: False)():
                    break
                try:
                    rp = _P(root)
                    if rp.is_dir():
                        resources.extend(
                            self._scan_project_caches_in_folder(
                                rp,
                                keep_recent_days=keep_recent_days,
                                enabled_categories=enabled_categories,
                                progress_callback=progress_callback,
                                cancel_event=cancel_event,
                            )
                        )
                except Exception:
                    continue
            return resources

    def cleanup_caches(self, resources: List[Dict], dry_run: bool = True,
                       progress_callback: Optional[object] = None,
                       cancel_event: Optional[object] = None) -> Dict:
        """Dispatch each scanned resource to its cleaner and aggregate results.

        Args:
            resources: Resource dicts as produced by scan_caches.
            dry_run: Passed through to the per-type cleaners; only some
                managers honor it (see _cleanup_manager_cache).
            progress_callback: Called as fn(done, total, freed_bytes).
            cancel_event: Set to stop before processing the next resource.

        Returns:
            Summary dict with success/freed/removed/errors plus per-resource
            results keyed by resource name.
        """
        total_freed = 0
        total_removed = 0
        errors = []
        results = {}
        total_count = len(resources)
        
        for idx, resource in enumerate(resources):
            if cancel_event and getattr(cancel_event, 'is_set', lambda: False)():
                break
                
            try:
                resource_type = resource.get("type")
                path = Path(resource.get("path", ""))
                
                if not path.exists():
                    continue
                
                if resource_type in ("python_cache", "project_cache"):
                    # Prefer cargo clean for Rust target folders
                    if path.name == "target" and (path.parent / "Cargo.toml").exists():
                        result = self.clean_cargo_project(path, dry_run)
                        # When cargo clean actually ran, we need freed estimate from scan
                        if not dry_run and not result.get("errors"):
                            result["freed"] = resource.get("size", 0)
                            result["removed"] = resource.get("file_count", 1)
                    else:
                        result = self._cleanup_python_cache(path, dry_run)
                elif resource_type == "package_manager_cache":
                    result = self._cleanup_manager_cache(
                        resource.get("manager_name"), 
                        dry_run
                    )
                else:
                    continue
                
                total_freed += result.get("freed", 0)
                total_removed += result.get("removed", 0)
                errors.extend(result.get("errors", []))
                results[resource.get("name", f"item_{idx}")] = result
                
                if progress_callback and callable(progress_callback):
                    progress_callback(idx + 1, total_count, total_freed)
                
            except Exception as e:
                error_msg = f"Error cleaning {resource.get('name', 'unknown')}: {e}"
                self.logger.error(error_msg)
                errors.append(error_msg)
        
        return {
            "success": len(errors) == 0,
            "freed": total_freed,
            "removed": total_removed,
            "errors": errors,
            "results": results,
            "dry_run": dry_run
        }
    
    def _cleanup_python_cache(self, cache_path: Path, dry_run: bool = True) -> Dict:
        """Delete every file under a project-cache directory.

        Contents (bytecode, tool/test caches, build outputs) are regenerated
        by the toolchain, so wholesale deletion is safe; the directory itself
        is removed only if it ends up empty.

        Args:
            cache_path: Cache directory to clean.
            dry_run: Count files/sizes without unlinking.

        Returns:
            Dict with freed bytes, removed count, errors, and dry_run echo.
        """
        freed = 0
        removed = 0
        errors = []
        
        if not cache_path.exists():
            return {"freed": 0, "removed": 0, "errors": []}
        
        try:
            for root, dirs, files in os.walk(cache_path):
                for file in files:
                    file_path = Path(root) / file
                    try:
                        file_size = file_path.stat().st_size
                        freed += file_size
                        removed += 1
                        
                        if not dry_run:
                            file_path.unlink()
                    except Exception as e:
                        errors.append(f"Could not remove {file_path}: {e}")
            
            # Try to remove empty directories
            if not dry_run:
                try:
                    if cache_path.exists() and not any(cache_path.iterdir()):
                        cache_path.rmdir()
                except Exception:
                    pass  # Directory not empty, that's okay
        
        except Exception as e:
            errors.append(f"Error cleaning {cache_path}: {e}")
        
        return {
            "freed": freed,
            "removed": removed,
            "errors": errors,
            "dry_run": dry_run
        }
    
    def _cleanup_manager_cache(self, manager_name: str, dry_run: bool = True) -> Dict:
        """Run the manager's native cache-clean command.

        Package lists are backed up first and freed space is inferred from
        before/after cache-size sampling. Only pip gets a true dry-run
        (reported as a would-free estimate); every other manager executes its
        real clean command regardless of dry_run.

        Args:
            manager_name: Key into self.package_managers.
            dry_run: Estimate-only for pip; ignored by other managers.

        Returns:
            Dict with freed/removed/errors, plus the backup path when a clean
            actually ran.
        """
        manager = self._get_manager_by_name(manager_name)
        if not manager:
            return {
                "freed": 0,
                "removed": 0,
                "errors": [f"Package manager {manager_name} not found"]
            }
        
        try:
            backup_result = self._backup_package_lists([manager_name])
            
            cache_size_before = self._get_cache_size(manager.cache_path)
            
            if dry_run:
                # pip has no dry-run mode; report current size as the estimate
                if manager_name in ["pip"]:
                    return {
                        "freed": cache_size_before,
                        "removed": 1,
                        "errors": [],
                        "note": f"Dry-run: Would clean {self._format_bytes(cache_size_before)}"
                    }
            
            config = self.package_managers[manager_name]
            clean_command = [manager.executable] + config["cache_clean_command"]
            
            result = _proc.run(clean_command, text=True, timeout=120)
            
            if result.returncode != 0:
                return {
                    "freed": 0,
                    "removed": 0,
                    "errors": [f"Clean command failed: {result.stderr}"]
                }
            
            cache_size_after = self._get_cache_size(manager.cache_path)
            freed = cache_size_before - cache_size_after
            
            return {
                "freed": freed,
                "removed": 1,
                "errors": [],
                "backup": backup_result.get(manager_name)
            }
        
        except Exception as e:
            return {
                "freed": 0,
                "removed": 0,
                "errors": [f"Cleanup failed: {e}"]
            }