"""Cortex Cleaner — Windows Hosts File Editor & Anti-Telemetry DNS Shield.

Inspects and manages the Windows Hosts file (%WinDir%\\System32\\drivers\\etc\\hosts):
1. Parses entries with IP mapping, hostname, comments, and enabled/disabled state.
2. Enables, disables, adds, and removes host records with automatic syntax validation.
3. Injects curated Windows Anti-Telemetry & Ad-Tracking blocklist rules.
4. Generates automated timestamped backups before applying modifications.
"""

from __future__ import annotations

import datetime
import os
import platform
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class HostEntry:
    """Host Entry data container."""
    ip: str
    hostname: str
    is_enabled: bool
    comment: str = ""
    raw_line: str = ""


# Curated Windows telemetry and tracking domains
ANTI_TELEMETRY_BLOCKLIST: List[str] = [
    "vortex.data.microsoft.com",
    "vortex-win.data.microsoft.com",
    "telemetry.microsoft.com",
    "telemetry.appex.bing.net",
    "watson.telemetry.microsoft.com",
    "watson.ppe.telemetry.microsoft.com",
    "settings-win.data.microsoft.com",
    "diagnostics.support.microsoft.com",
    "feedback.microsoft-hohm.com",
    "choice.microsoft.com",
    "choice.microsoft.com.nsatc.net",
    "df.telemetry.microsoft.com",
    "reports.wes.df.telemetry.microsoft.com",
    "wes.df.telemetry.microsoft.com",
]


@dataclass
class HostsOperationResult:
    """Hosts Operation Result data container."""
    success: bool
    message: str
    backup_path: Optional[str] = None
    error: Optional[str] = None


class HostsFileManager:
    """Production Windows Hosts file and Anti-Telemetry DNS manager."""

    @classmethod
    def get_hosts_path(cls) -> Path:
        """Locate hosts file path across platforms."""
        if platform.system() == "Windows":
            windir = os.environ.get("WINDIR", r"C:\Windows")
            return Path(windir) / "System32" / "drivers" / "etc" / "hosts"
        return Path("/etc/hosts")

    @classmethod
    def parse_hosts_file(cls, hosts_path: Optional[Path] = None) -> List[HostEntry]:
        """Parse hosts file into structured entries."""
        path = hosts_path or cls.get_hosts_path()
        if not path.is_file():
            return []

        entries: List[HostEntry] = []
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    stripped = line.strip()
                    if not stripped:
                        continue

                    is_enabled = not stripped.startswith("#")
                    content = stripped.lstrip("#").strip()

                    # Extract inline comment if any
                    comment = ""
                    if "#" in content:
                        parts = content.split("#", 1)
                        content = parts[0].strip()
                        comment = parts[1].strip()

                    tokens = content.split()
                    if len(tokens) >= 2:
                        ip = tokens[0]
                        for host in tokens[1:]:
                            entries.append(HostEntry(
                                ip=ip,
                                hostname=host,
                                is_enabled=is_enabled,
                                comment=comment,
                                raw_line=line.rstrip("\r\n"),
                            ))
        except Exception:
            pass

        return entries

    @classmethod
    def _create_backup(cls, hosts_path: Path) -> Optional[Path]:
        """Create a timestamped backup before modifying the hosts file."""
        try:
            backup_dir = Path.home() / ".cortex_backups" / "hosts"
            backup_dir.mkdir(parents=True, exist_ok=True)
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_file = backup_dir / f"hosts_backup_{ts}.txt"
            shutil.copy2(hosts_path, backup_file)
            return backup_file
        except Exception:
            return None

    @classmethod
    def save_hosts_entries(cls, entries: List[HostEntry], hosts_path: Optional[Path] = None) -> HostsOperationResult:
        """Write modified host entries back to the hosts file."""
        path = hosts_path or cls.get_hosts_path()
        backup_p = cls._create_backup(path)

        lines: List[str] = [
            "# Generated by Cortex Cleaner Hosts Manager",
            f"# Last updated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        for e in entries:
            prefix = "" if e.is_enabled else "# "
            cmt_str = f" # {e.comment}" if e.comment else ""
            lines.append(f"{prefix}{e.ip:<15} {e.hostname}{cmt_str}")

        lines.append("")

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            return HostsOperationResult(
                success=True,
                message=f"Hosts file successfully updated ({len(entries)} rules).",
                backup_path=str(backup_p) if backup_p else None,
            )
        except Exception as exc:
            return HostsOperationResult(
                success=False,
                message=f"Failed to write hosts file (Admin rights required): {exc}",
                backup_path=str(backup_p) if backup_p else None,
                error=str(exc),
            )

    @classmethod
    def apply_anti_telemetry_shield(cls, hosts_path: Optional[Path] = None) -> HostsOperationResult:
        """Inject anti-telemetry blocklist rules into hosts file."""
        current_entries = cls.parse_hosts_file(hosts_path)
        existing_hosts = {e.hostname.lower() for e in current_entries if e.is_enabled}

        added = 0
        for block_domain in ANTI_TELEMETRY_BLOCKLIST:
            if block_domain.lower() not in existing_hosts:
                current_entries.append(HostEntry(
                    ip="0.0.0.0",
                    hostname=block_domain,
                    is_enabled=True,
                    comment="Cortex Anti-Telemetry Shield",
                ))
                added += 1

        if added == 0:
            return HostsOperationResult(True, "Anti-Telemetry Shield is already fully active (all domains blocked).")

        return cls.save_hosts_entries(current_entries, hosts_path)
